# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'anchor' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  
  node_modules_path = '../node_modules'
  react_path = File.join(node_modules_path, 'react-native')
  yoga_path = File.join(react_path, 'ReactCommon/yoga')
  
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'

  # Pods for anchor
  pod 'yoga', path: yoga_path
  pod 'React', path: react_path, :subspecs => [
  'Core',
  'DevSupport', # Devmenu
  'RCTWebSocket', # needed for debugging
  'RCTLinkingIOS',
  'RCTNetwork',
  'RCTPushNotification',
  'RCTAnimation',
  ]

  # Pods for FBSDK
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKPlacesKit'
  pod 'FBSDKMessengerShareKit'
  
  #Required by RNGoogleSignin
  pod 'GoogleSignIn'

  # Required by RNFirebase
  pod 'Firebase/Core', '~> 5.11.0'
  
  #RNFirebase Auth Package
  pod 'Firebase/Auth', '~> 5.11.0'
  
  #RNFirebase Cloud Messaging Package
  pod 'Firebase/Messaging', '~> 5.11.0'
  
  #RNFirebase Firestore Package
  pod 'Firebase/Firestore', '~> 5.11.0'

  #RN Linear Gradient Package
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'

  #RN Vector Icons package
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  
  #RN Google Places package
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'GooglePlacePicker'

end
