# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'anchor' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for anchor
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native'
  
  # Pods for FBSDK
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'FBSDKPlacesKit'
  pod 'FBSDKMessengerShareKit'
    
  # Required by RNFirebase
  pod 'Firebase/Core'
  
  #RNFirebase Auth Package
  pod 'Firebase/Auth'
  
  #RNFirebase Cloud Messaging Package
  pod 'Firebase/Messaging'
  
  #RNFirebase Firestore Package
  pod 'Firebase/Firestore'


  target 'anchorTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
